import time
import streamlit as st
from psycopg2.extras import Json
import os
import re
from datetime import datetime
import uuid
from db_operations import get_pg_connection
from restaurant_config import *
from validators import *
from image_processing import extract_menu_from_image
import hashlib
import secrets
from caterer_operations import *
from orders_operations import *
from utils import extract_date_from_menu_id,menu_to_single_dataframe,format_datetime,date_converter,download_button_built_in,get_base64_image
from admin_operations import get_caterer_by_caterer_id
from templatecss import apply_custom_css


def load_menu_catalog():
    """Load menu catalog from database"""
    conn = get_pg_connection()
    cursor = conn.cursor()
    try:
        cursor.execute("""
            SELECT menu_item_id,item_name,description,default_price,category
            FROM menu_catalog
        """)
        
        menu_catalog = cursor.fetchall()
        print(f"Menu catalog: {menu_catalog}")
        menu_catalog_dict = []
        
        for menuitem in menu_catalog:

            order = {
                "Item Id": menuitem['menu_item_id'],
                "Item Name": menuitem['item_name'],
                "Description": menuitem['description'] ,
                "Default Price": menuitem ['default_price'],
                "Category": menuitem ['category'] 
            }
            
            menu_catalog_dict.append(order)
            menu_catalog_dict_df=pd.DataFrame(menu_catalog_dict)

            return menu_catalog_dict_df
    except Exception as e:
        print(f"Error loading Menu Catalog: {e}")
        return []
        
    finally:
        cursor.close()
        conn.close()
        
    return menu_catalog_dict_df

def get_menu_catalog():
    """
    Load existing Menu Catalog and Add new items to Catalog
    """
    # Connect to the database
    conn = get_pg_connection()
    cursor = conn.cursor()
    try:
        cursor.execute("""
            SELECT menu_item_id,item_name,description,default_price,category
            FROM menu_catalog
        """)
        
        menu_catalog = cursor.fetchall()
        print(f"Menu catalog: {menu_catalog}")
        menu_catalog_dict = []
        
        for menuitem in menu_catalog:

            order = {
                "Item Id": menuitem['menu_item_id'],
                "Item Name": menuitem['item_name'],
                "Description": menuitem['description'] ,
                "Default Price": menuitem ['default_price'],
                "Category": menuitem ['category'] 
            }
            
            menu_catalog_dict.append(order)
        
        return menu_catalog_dict
        
    except Exception as e:
        print(f"Error loading Menu Catalog: {e}")
        return []
        
    finally:
        cursor.close()
        conn.close()

    return

def save_changes_to_db(original_df, edited_df):
    """Save changes to database"""
    conn = get_pg_connection()
    if not conn:
        return False
    
    try:
        cursor = conn.cursor()
        
        # Find deleted rows (in original but not in edited)
        if len(original_df) > 0:
            original_ids = set(original_df['Item Id'].dropna())
            edited_ids = set(edited_df['Item Id'].dropna()) if 'Item Id' in edited_df.columns else set()
            deleted_ids = original_ids - edited_ids
            
            # Delete removed items
            for item_id in deleted_ids:
                cursor.execute("DELETE FROM menu_catalog WHERE menu_item_id = %s", (int(item_id),))
        
            # Process each row in edited data
            for idx, row in edited_df.iterrows():
                if pd.isna(row.get('Item Id')) or row.get('Item Id') == '' or row.get('Item Id') is None:
                    # New record - INSERT (menu_item_id will be auto-generated by menu_item_id_seq)
                    cursor.execute("""
                        INSERT INTO menu_catalog (item_name, description, default_price, category)
                        VALUES (%s, %s, %s, %s)
                    """, (
                        str(row['Item Name']) if pd.notna(row['Item Name']) else '',
                        str(row.get('Description', '')) if pd.notna(row.get('Description')) else '',
                        float(row['Default Price']) if pd.notna(row['Default Price']) else 0.0,
                        str(row.get('Category', '')) if pd.notna(row.get('Category')) else ''
                    ))
        else:
            # Existing record - UPDATE using existing menu_item_id
            try:
                menu_item_id = int(row['Item Id'])
                cursor.execute("""
                    UPDATE menu_catalog 
                    SET item_name = %s, description = %s, default_price = %s, category = %s
                    WHERE menu_item_id = %s
                """, (
                    str(row['Item Name']) if pd.notna(row['item_name']) else '',
                    str(row.get('Description', '')) if pd.notna(row.get('description')) else '',
                    float(row['Default Price']) if pd.notna(row['default_price']) else 0.0,
                    str(row.get('category', '')) if pd.notna(row.get('category')) else '',
                    menu_item_id
                ))
            except (ValueError, TypeError):
                # If menu_item_id is invalid, treat as new record (sequence will generate ID)
                cursor.execute("""
                    INSERT INTO menu_catalog (item_name, description, default_price, category)
                    VALUES (%s, %s, %s, %s)
                """, (
                    str(row['item_name']) if pd.notna(row['item_name']) else '',
                    str(row.get('description', '')) if pd.notna(row.get('description')) else '',
                    float(row['default_price']) if pd.notna(row['default_price']) else 0.0,
                    str(row.get('category', '')) if pd.notna(row.get('category')) else ''
                ))

        conn.commit()
        cursor.close()
        conn.close()
        return True
        
    except Exception as e:
        st.error(f"Error saving changes: {e}")
        conn.rollback()
        cursor.close()
        conn.close()
        return False
    

def display_menu_catalog():

    st.subheader("Menu Catalog")
    if 'menu_catalog_df' not in st.session_state:
        with st.spinner("Loading data from database..."):
            st.session_state.menu_catalog_df = load_menu_catalog()
            st.session_state.original_df = st.session_state.menu_catalog_df.copy()
        
    if len(st.session_state.menu_catalog_df) > 0:
        st.success(f"Loaded {len(st.session_state.menu_catalog_df)} records from database")
    else:
        st.warning("No data loaded. Check database connection and table.")
    
        
    columns_to_show = [col for col in st.session_state.menu_catalog_df.columns if col != 'Item Id']
    edited_df = st.data_editor(
                st.session_state.menu_catalog_df[columns_to_show],
                num_rows="dynamic",  # Allow adding/deleting rows
                use_container_width=True,
                key="menu_editor"
            )
    

    # Add back menu_item_id for existing rows, leave empty for new rows
    if len(edited_df) > 0:
        # Create a new dataframe with menu_item_id
        result_df = edited_df.copy()
        
        # Add menu_item_id column
        if len(st.session_state.menu_catalog_df) > 0:
            # Match existing rows by index, new rows get NaN
            id_column = st.session_state.menu_catalog_df.columns[0]
            original_ids = st.session_state.menu_catalog_df[id_column].tolist()
            menu_ids = []
            
            for i in range(len(result_df)):
                if i < len(original_ids):
                    menu_ids.append(original_ids[i])
                else:
                    menu_ids.append(None)  # New row
            
            result_df.insert(0, 'Item Id', menu_ids)
        else:
            result_df.insert(0, 'Item Id', [None] * len(result_df))
    else:
        result_df = pd.DataFrame(columns=['Item Id', 'Item Name', 'Description', 'Default Price', 'Category'])

    # Show changes summary
    if 'original_df' in st.session_state:
        original_count = len(st.session_state.original_df)
        current_count = len(result_df)
        new_rows = len([x for x in result_df['Item Id'] if pd.isna(x)])
        
        col1, col2, col3 = st.columns(3)
        with col1:
            st.metric("Original Records", original_count)
        with col2:
            st.metric("Current Records", current_count, current_count - original_count)
        with col3:
            st.metric("New Records", new_rows)
    
    # Save changes button
    st.divider()
    col1, col2 = st.columns([1, 4])
    if 'saving_changes' not in st.session_state:
        st.session_state.saving_changes = False
    
    # Validate records before enabling save button
    def validate_records(df):
        if len(df) == 0:
            return False, "No data to save"
        
        # Check for required fields
        for idx, row in df.iterrows():
            # Check if item_name is missing or empty
            if pd.isna(row.get('item_name')) or str(row.get('item_name', '')).strip() == '':
                return False, f"Row {idx + 1}: Item name is required"
            
            # Check if default_price is missing or invalid
            try:
                price = float(row.get('default_price', 0))
                if price <= 0:
                    return False, f"Row {idx + 1}: Price must be greater than 0"
            except (ValueError, TypeError):
                return False, f"Row {idx + 1}: Invalid price format"
        
        return True, "Valid records"
    
    is_valid, validation_message = validate_records(result_df)
    # Show validation message if invalid
    if not is_valid:
        st.caption(f"⚠️ {validation_message}")
    
    with col1:
            save_button=st.button("💾 Save Changes", 
                     type="primary",
                     disabled=st.session_state.saving_changes or not is_valid,
                     key="save_changes_btn")
            
            if save_button and not st.session_state.saving_changes and is_valid:
            # Set saving state to disable button
                st.session_state.saving_changes = True
            
            with st.spinner("Saving changes to database..."):
                success = save_changes_to_db(
                    st.session_state.get('original_df', pd.DataFrame()), 
                    result_df
                )
                
                if success:
                    st.success("✅ Changes saved successfully!")
                    # Reload data to show updated IDs
                    st.session_state.menu_catalog_df = load_menu_catalog()
                    st.session_state.original_df = st.session_state.menu_catalog_df.copy()
                    # Reset saving state
                    st.session_state.saving_changes = False
                    st.rerun()
                else:
                    st.error("❌ Failed to save changes. Check database connection.")
                    # Reset saving state on error
                    st.session_state.saving_changes = False
    
    with col2:
        st.caption("💡 New items will get auto-generated IDs when saved to database")

    return